# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6edcc7b5b8ca04c94e6ec4fc6ad04b4d8d077c60cf18b509eafbc235ce02e09bebea5d8223177a394c7fa7fdd320e022bda45b93570bc30e9016687ca3b54396

test:
  secret_key_base: e2f1f3bec93c6477ba28a0331b952e2eff938ec1f39e98e8daf16c757f171c64feae6392aad9b06f6fbdc374d7714c0f5184e5f885765278aa95ca93fed9dd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
